###Worksheet 0

##Importing All the necessary Libraries

In [39]:
import numpy as np
import time

##Problem - 1:Array Creation

1. Initializating Empty Array (2*2)

In [40]:
array = np.empty((2,2))
array #it contains garbage values

array([[0., 0.],
       [0., 0.]])

In [41]:
array = np.zeros((2,2))
array #intitilizing zero

array([[0., 0.],
       [0., 0.]])

In [42]:
array = np.full((2, 2), 15)
array #15

array([[15, 15],
       [15, 15]])

2.Initializing all one array (4*2)

In [43]:
array = np.ones((4,2), dtype=int) #integer type float
array

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [44]:
array = np.full ((4,2), 1)
array

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

3. A new array of given shape and type, filled with fill value.{Hint: np.full}

In [45]:
array =np.full((4,4),7, dtype=int)
array

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

4. New array of zeros with same shape and type as given array

In [46]:
array = np.full((4, 4), 8)
new_array = np.zeros_like(array)
new_array

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

###5. New array of ones with same shape and type as given array

In [47]:
array = np.full((4, 3), 8)
new_array = np.ones_like(array)
new_array

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [48]:
new_list = [1, 2, 3, 4]
np_list = np.array(new_list)
print("Normal List: ", new_list)
print("Numpy List: ", np_list)

Normal List:  [1, 2, 3, 4]
Numpy List:  [1 2 3 4]


##Problem - 2: Array Manipulation: Numerical Ranges and Array Indexing

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [49]:
arr = np.arange (10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

2. Create a 3X3 matrix with values ranging from 0 to 8.

In [50]:
arr = np.arange(0, 9)
reshaped = np.reshape(arr, (3, 3))
print(arr)
print(reshaped)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.

In [51]:
array =np.eye (3, dtype=int)
array

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

4. Create a random array of size 30 and find the mean of the array.

In [52]:
random_array = np.random.random(30)

mean_array = random_array.mean()

print(random_array)
print("Mean: ", mean_array)

[0.64195886 0.23205056 0.04050533 0.4605767  0.56394976 0.08411532
 0.56165319 0.93007714 0.69359497 0.76932052 0.80270174 0.45622613
 0.72135693 0.85210879 0.83641182 0.90579787 0.53251151 0.63367972
 0.35388658 0.82680116 0.46932294 0.61284735 0.81530621 0.86945959
 0.52519205 0.9623494  0.66843293 0.78069895 0.45418329 0.15024328]
Mean:  0.6069106862247983


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [53]:
# random_arr = np.random.random((10, 10))
random_arr = np.random.randint(1, 10, (10, 10))
min = random_arr.min()
max = random_arr.max()

print(random_arr)
print()
print("Min: ", min)
print("Max: ", max)

[[8 2 6 5 3 7 9 7 2 4]
 [6 4 3 6 2 6 1 4 2 8]
 [7 1 1 7 7 9 7 3 4 7]
 [9 6 3 7 1 8 9 3 7 2]
 [9 4 7 5 9 7 7 4 7 8]
 [2 2 9 2 1 2 2 6 2 9]
 [7 1 2 9 4 7 8 9 6 4]
 [9 5 4 9 4 1 7 6 9 3]
 [4 5 1 5 4 7 2 7 5 6]
 [6 2 3 9 4 8 4 7 3 9]]

Min:  1
Max:  9


6. Create a zero array of size 10 and replace 5th element with 1.

In [54]:
array = np.zeros(10, dtype=int)
print(array)
array[4] = 1
print(array)

[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0]


7. Reverse an array arr = [1,2,0,0,4,0].

In [55]:
arr = [1,2,0,0,4,0]
rev_arr = arr[::-1]
rev_arr

[0, 4, 0, 0, 2, 1]

8. Create a 2d array with 1 on border and 0 inside.

In [56]:
arr = np.random.randint(1, 10, (7, 7))

# arr = np.zeros_like(arr)
arr[0, :] = 1
arr[-1, :] = 1
arr[:, 0] = 1
arr[:, -1] = 1

arr[0:-1, 1:-1] = 0

arr

array([[1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1]])

9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [57]:
array = np.zeros((9, 9), dtype=int)

array[1::2, 0::2] = 1
array[::2, 1::2] = 1
array

array([[0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0]])

##Problem - 3: Array Operations

In [58]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

Complete all the task using numpy:
1. Add the two array.

In [59]:
sum = x + y
sum1 = v + w
print(sum)
print()
print(sum1)

[[ 6  8]
 [10 13]]

[20 22]


2. Subtract the two array.

In [60]:
sub = x - y
sub1 = v - w
print(sub)
print()
print(sub1)

[[-4 -4]
 [-4 -3]]

[-2 -2]


3. Multiply the array with any integers of your choice.

In [73]:
multiplyArray = 7* x
multiplyArray

array([[ 7, 14],
       [21, 35]])

4. Find the square of each element of the array.

In [62]:
powerArray = x ** 2
powerArray

array([[ 1,  4],
       [ 9, 25]])

Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [63]:
vDotw = np.dot(v, w)
xDotv = np.dot(x, v)
xDoty = np.dot(x, y)

print(f"V.W: {vDotw}")
print(f"X.V: {xDotv}")
print(f"X.Y: \n{xDoty}")

V.W: 219
X.V: [29 77]
X.Y: 
[[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [64]:
conxy = np.concatenate((x, y), axis = 0)
convw = np.vstack((v, w))
print(conxy)
print()
print(convw)

[[1 2]
 [3 5]
 [5 6]
 [7 8]]

[[ 9 10]
 [11 12]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [66]:
conxv = np.concatenate((x, v), axis = 0)
conxv
#ERROR is caused the arrays should have the same number of dimensions
#x is a 2D array where as v is a 1D array

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

##Problem - 4: Matrix Operations:

In [67]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

1. Prove A.A−1 = I.

In [68]:
InverseOF_A = np.linalg.inv(A)
proof = np.round(np.matmul(A, InverseOF_A))
proof

array([[1., 0.],
       [0., 1.]])

2. Prove AB ̸= BA.

In [69]:
AB = np.matmul(A, B)
BA = np.matmul(B, A)

print(f"AB:\n{AB} \nBA:\n{BA}")

AB:
[[23 13]
 [51 29]] 
BA:
[[36 44]
 [13 16]]


3. Prove (AB)T = BTAT

In [70]:
AB = np.matmul(A, B)
AB_T = AB.T
B_T = B.T
A_T = A.T
B_T_Dot_A_T = np.matmul(B_T, A_T)

print(f"AB_T: \n{AB_T} \n\n B_T.A_T: \n{B_T_Dot_A_T}")

AB_T: 
[[23 51]
 [13 29]] 

 B_T.A_T: 
[[23 51]
 [13 29]]


Solve the following system of Linear equation using Inverse Methods.

In [71]:
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1,  -1]])
B = np.array([-1, -3, 9])

A_Inverse = np.linalg.inv(A)

X = np.matmul(A_Inverse, B)

print(f"[x y z] = {X}")

[x y z] = [ 2.  1. -2.]


##Numpy Speed

In [75]:
import builtins  # Ensures we use the original Python sum() function

size = 1000000
matrices = 1000

# Lists for normal Python operations
pyArray1 = list(range(size))
pyArray2 = list(range(size))

# NumPy arrays for optimized operations
npArray1 = np.arange(size)
npArray2 = np.arange(size)

# Addition Benchmark
sTime = time.time()
pySum = [pyArray1[i] + pyArray2[i] for i in range(size)]
pyTimeAdd = time.time() - sTime

sTime = time.time()
npSum = npArray1 + npArray2
npTimeAdd = time.time() - sTime

print(f"Addition Time: \nNumpy: {npTimeAdd:.5f} \nNormal Py list: {pyTimeAdd:.5f}\n")

# Element-wise Multiplication Benchmark
sTime = time.time()
pyMul = [pyArray1[i] * pyArray2[i] for i in range(size)]
pyTimeMul = time.time() - sTime

sTime = time.time()
npMul = npArray1 * npArray2
npTimeMul = time.time() - sTime

print(f"Element Multiplication Time: \nNumpy: {npTimeMul:.5f} \nNormal Py list: {pyTimeMul:.5f}\n")

# Dot Product Benchmark
sTime = time.time()
pyDot = builtins.sum(pyArray1[i] * pyArray2[i] for i in range(size))  # Ensuring sum() is not overridden
pyTimeDot = time.time() - sTime

sTime = time.time()
npDot = np.dot(npArray1, npArray2)
npTimeDot = time.time() - sTime

print(f"Dot Product Time: \nNumpy: {npTimeDot:.5f} \nNormal Py list: {pyTimeDot:.5f}\n")

# Matrix Multiplication Setup
pyMat1 = [[j for j in range(matrices)] for i in range(matrices)]
pyMat2 = [[j for j in range(matrices)] for i in range(matrices)]

npMat1 = np.arange(matrices**2).reshape(matrices, matrices)
npMat2 = np.arange(matrices**2).reshape(matrices, matrices)

# Matrix Multiplication Benchmark
sTime = time.time()
pyMatMul = [[builtins.sum(pyMat1[i][k] * pyMat2[k][j] for k in range(matrices)) for j in range(matrices)] for i in range(matrices)]
pyTimeMatMul = time.time() - sTime

sTime = time.time()
npMatMul = np.dot(npMat1, npMat2)
npTimeMatMul = time.time() - sTime

print(f"Matrix Multiplication Time: \nNumpy: {npTimeMatMul:.5f} \nNormal Py list: {pyTimeMatMul:.5f}\n")


Addition Time: 
Numpy: 0.00135 
Normal Py list: 0.04972

Element Multiplication Time: 
Numpy: 0.00127 
Normal Py list: 0.15213

Dot Product Time: 
Numpy: 0.00180 
Normal Py list: 0.06014

Matrix Multiplication Time: 
Numpy: 0.91554 
Normal Py list: 137.21934

